# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf44253dde19f7684721df9bba26d97952cbdda120ae2df8dc7fa21382fc2b5cd67e9a3589653ad667dbb11631b0321ba46cc2b5bd0bda679593cbdf3a133194

test:
  secret_key_base: fa3de3b2338f3537a011b123a35b2e33ffae5a022b14d0888e5f919f9e977a7af5105747cde2523c438198794aad970fc6d9a7b4fefbe79182d791782edf4a3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
